"""Add num_persons to Booking model

Revision ID: b287b2be4cb5
Revises: d8b4f63e5b9a
Create Date: 2025-06-18 09:22:17.144381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b287b2be4cb5'
down_revision = 'd8b4f63e5b9a'
branch_labels = None
depends_on = None


def upgrade():
    # Add the column as nullable first
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_persons', sa.Integer(), nullable=True))

    # Set default value for all existing rows
    op.execute('UPDATE booking SET num_persons = 1 WHERE num_persons IS NULL')

    # Alter the column to be non-nullable
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('num_persons', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('num_persons')

    # ### end Alembic commands ###
