"""Add user_deleted to Booking for soft delete

Revision ID: cc268032e7e4
Revises: b287b2be4cb5
Create Date: 2025-06-18 16:56:16.388984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc268032e7e4'
down_revision = 'b287b2be4cb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('user_deleted')

    # ### end Alembic commands ###
