"""Add UPI reference and payment status to Booking

Revision ID: d8b4f63e5b9a
Revises: 1d4f93729d7c
Create Date: 2025-06-18 07:21:13.478385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8b4f63e5b9a'
down_revision = '1d4f93729d7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upi_reference', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('upi_reference')

    # ### end Alembic commands ###
